History Window
kaczy93/centredsharp pull request #22
Opened 2024-03-24 00:05 UTC by Mink80

with friendly greetings from UO SAGAS

2024-03-24 09:09 UTC, 3HMonkey approved these changes

2024-03-24 09:10 UTC, 3HMonkey approved these changes

2024-03-24 09:11 UTC, 3HMonkey approved these changes

2024-03-24 09:59 UTC, 3HMonkey commented
Still a bug inside. Do not merge for the moment. Ill check it.

2024-03-24 10:19 UTC, 3HMonkey requested changes
You'll need to wait for the table to setup first when rendering its content, so you have to use its' content inside the clause. 

Example:
```csharp
if (ImGui.BeginTable("UndoTable", 2, ImGuiTableFlags.Borders | ImGuiTableFlags.SizingFixedFit))
{
    // Your doing here
    ImGui.EndTable();
}
```

So please replace:

```csharp
// Create table
ImGui.BeginTable("UndoTable", 2, ImGuiTableFlags.Borders | ImGuiTableFlags.SizingFixedFit);

// Set column widths
ImGui.TableSetupColumn("Task", ImGuiTableColumnFlags.WidthFixed, 120);
ImGui.TableSetupColumn("Details", ImGuiTableColumnFlags.WidthFixed, 350);

// Headers
ImGui.TableHeadersRow();

var cnt = 0;
foreach (var command in CEDClient.UndoStack)
{
    cnt++;
    ImGui.TableNextRow();
    ImGui.TableNextColumn();
    GetHistory(command[0], out var task, out var details);
    ImGui.Text(task);
    ImGui.TableNextColumn();
    ImGui.Text(details);

    if (cnt >= 25)
    {
        break;
    }
}
ImGui.EndTable();
```

with

```csharp
if (ImGui.BeginTable("UndoTable", 2, ImGuiTableFlags.Borders | ImGuiTableFlags.SizingFixedFit))
{
    // Set column widths
    ImGui.TableSetupColumn("Task", ImGuiTableColumnFlags.WidthFixed, 120);
    ImGui.TableSetupColumn("Details", ImGuiTableColumnFlags.WidthFixed, 350);

    // Headers
    ImGui.TableHeadersRow();

    var cnt = 0;
    foreach (var command in CEDClient.UndoStack)
    {
        cnt++;
        ImGui.TableNextRow();
        ImGui.TableNextColumn();
        GetHistory(command[0], out var task, out var details);
        ImGui.Text(task);
        ImGui.TableNextColumn();
        ImGui.Text(details);

        if (cnt >= 25)
        {
            break;
        }
    }
    ImGui.EndTable();
}
```

2024-03-24 10:25 UTC, Mink80 commented
Thank you @3HMonkey. Done.

2024-03-24 10:28 UTC, 3HMonkey approved these changes
Approved and runs. Good thing!

2024-03-25 09:57 UTC, kaczy93 commented on CentrED/UI/Windows/HistoryWindow.cs
> +                if (cnt >= 25)
Why do we limit to only 25 entries? ImGUI is very good at providing a scrolling interface if stuff wouldn't fit inside the window and if this is due to performance we can use the imgui list clipper

2024-03-25 09:57 UTC, kaczy93 commented on CentrED/UI/Windows/HistoryWindow.cs
> +        details = "Error parsing packet"; // should never be shown
This should be in the `default` block :)

2024-03-25 09:57 UTC, kaczy93 commented on CentrED/UI/Windows/HistoryWindow.cs
> +                if (command.Length == 1)
I think we can make it nicer if we don't repeat the code.
Something like this
```csharp
var isGroup = command.Length > 1
if (isGroup){
    ImGui.TableNextRow();
    ImGui.TableNextColumn();
    ImGui.Text("Task collection");
}
foreach (var packet in command)
{
    ImGui.TableNextRow();
    ImGui.TableNextColumn();
    GetHistory(packet, out var task, out var details);
    ImGui.Text($"{isGroup ? "\t " : ""}{task}");
    ImGui.TableNextColumn();
    ImGui.Text(details);
}
```

2024-03-25 09:57 UTC, kaczy93 commented on Client/Packets.cs
> +        TileId = tileId;
It feels weird that we omit hue :)
Also applies to other static packets

2024-04-03 06:57 UTC, merged